---
- hosts: dev
  become: True
  
  vars:
    container_count: 1
    default_container_name: javaapp
    default_container_image: arvinthganesan/javaapp
    default_container_command: sleep 1
  
  tasks:
   - name: update repo
     apt:
      name: "*"
      state: present
       
    
   - name: Install required system packages
     apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
       
       
       
       
       
   - name: Install python pip
     apt:
        name: python3-pip
        state: present
    
   - name: installa dependency
     apt:
        name: "{{item}}"
        state: present
        update_cache: yes
     loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        
   - name: add GPG key
     apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
   - name: add docker repository to apt
     apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
        
   - name: install docker
     apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
     loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        
   - name: assicurati che docker sia attivo
     service:
        name: docker
        state: started
        enabled: yes
        
   - name: Install Docker Module for Python
     pip:
       name: docker
        
   - name: pull an image
     docker_image:
       name: arvinthganesan/javaapp
       source: pull

   - name: deploy docker container
     docker_container:
        image: javaapp:stable
        name: javaapp
        state: started
        auto_remove: true
        ports:
          - "8080:80"
