---
- hosts: dev
  become: True
  tasks:
    - name: Install python2 pip
      ansible.builtin.apt:
        name: python-pip
        state: present
    - name: Install docker
      ansible.builtin.apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: javaapp
        image: "arvinthganesan/javaapp:${{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
